---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-cloud-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybrid-cloud-frontend
  template:
    metadata:
      labels:
        app: hybrid-cloud-frontend
    spec:
      serviceAccountName: hybrid-cloud-demo-sa
      containers:
        - image: quay.io/rhdevelopers/hybrid-cloud-demo-frontend
          imagePullPolicy: IfNotPresent
          name: hybrid-cloud-frontend
          env:
            - name: IO_OPENSHIFT_BOOSTER_MESSAGING_BACKENDSERVICE_MP_REST_URL
              value: http://hybrid-cloud-backend-skupper
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 1200Mi
              cpu: 750m
            requests:
              memory: 500Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
